version: "3.0"
services:
  workshop:
    image: ghcr.io/vmware-tanzu-labs/educates-base-environment:develop 
    user: 1001:0
    ports:
    - "127.0.0.1:10081:10081"
    volumes:
    - .:/opt/assets/files:rw
    depends_on:
    - grafana-workshop
    - influxdb-workshop
  grafana-workshop:
    image: grafana/grafana:7.1.3
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
  influxdb-workshop:
    image: influxdb:1.8.1
    environment:
    - INFLUXDB_DB=wsgi
    - INFLUXDB_USER=wsgi
    - INFLUXDB_USER_PASSWORD=wsgi
