version: '2.0'
services:
  workshop:
    image: quay.io/eduk8s/base-environment:develop
    environment:
    - INGRESS_PORT_SUFFIX=:10081
    ports:
    - "10081:10080"
    volumes:
    - ./resources/workshop.yaml:/opt/eduk8s/config/workshop.yaml:ro
    depends_on:
    - workshop-grafana
    - workshop-influxdb
    extra_hosts:
    - workshop-editor:127.0.0.1
  workshop-grafana:
    image: docker.io/grafana/grafana:7.1.3
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
  workshop-influxdb:
    image: docker.io/influxdb:1.8.1
    environment:
    - INFLUXDB_DB=wsgi
    - INFLUXDB_USER=wsgi
    - INFLUXDB_USER_PASSWORD=wsgi
