apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-mod-wsgi-metrics
spec:
  title: Generating metrics from mod_wsgi
  description: An introductory workshop on generating metrics from mod_wsgi.
  difficulty: beginner
  duration: 60m
  url: https://github.com/eduk8s/lab-mod-wsgi-metrics
  content:
    files: github.com/GrahamDumpleton/lab-mod-wsgi-metrics
  workshop:
    files:
    - image:
        url: $(image_repository)/lab-mod-wsgi-metrics:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /bin/**
  session:
    namespaces:
      budget: small
      security:
        token:
          enabled: false
    applications:
      terminal:
        enabled: true
        layout: split
      editor:
        enabled: true
      docker:
        enabled: true
        compose:
          version: "3.0"
          services:
            grafana-workshop:
              image: grafana/grafana:7.1.3
              ports:
              - "127.0.0.1:3000:3000"
              environment:
              - GF_AUTH_ANONYMOUS_ENABLED=true
            influxdb-workshop:
              image: influxdb:1.8.1
              ports:
              - "127.0.0.1:8086:8086"
              environment:
              - INFLUXDB_DB=wsgi
              - INFLUXDB_USER=wsgi
              - INFLUXDB_USER_PASSWORD=wsgi
    ingresses:
    - name: grafana
      host: grafana-$(session_namespace)
      port: 3000
    - name: influxdb
      host: influxdb-$(session_namespace)
      port: 8086
    dashboards:
    - name: Grafana
      url: $(ingress_protocol)://grafana-$(session_namespace).$(ingress_domain)$(ingress_port_suffix)/
